;(function(root, newsService) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register component as an anonymous module
        define(newsService);
    } else if (typeof exports === 'object') {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like environments that support module.exports,
    	// like Node.
        module.exports = newsService();
    } else {
        // Browser globals. Register component on window
        root.NewsService = newsService();
    }
})(this, function() {
  'use strict';

  /*
    This is a mock products service to simulate loading a list of products from the backend.
  */
  var NewsService = function() {

    var mockOverviewData = [
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">Knud Holscher Exhibition<br>opening on January 29!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum.</p><a href="#" class="link news-box__link">read more</a></div>',
      '<div class="news-box"><div class="news-box__date text">february 9, 2017</div><a href="#"><h3 class="news-box__title header-small">100 ton of Danish Design will be installed in Oslo!</h3></a><p class="news-box__text text">Phasellus fringilla lacinia tortor ut auctor. Praesent vel faucibus quam, at convallis odio.</p><a href="#" class="link news-box__link">read more</a></div>',
    ];


    var mockDetailsData = [
      '<div class="news-details gl-bot gl-bot--pull-left"><div class="news-details__header"><span class="news-details__meta text">februrary 9, 2017</span><h1 class="header-large"><strong>100 ton of Danish<br>Design will be installed in Oslo!</strong></h1></div><div class="news-details__row"><div class="news-details__author-col"><span class="text author">by Knud Holscher</span></div><div class="news-details__article-col article"><div class="article__rich-text text"><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor,sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p></div></div><div class="news-details__img-col gl-left-lg"><div class="news-details__img lazy-image lazy-image--loaded"><img data-src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg" class="lazy-image__image" src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg"><div class="cell-load__overlay" style=""></div></div></div></div></div>',
      '<div class="news-details gl-bot gl-bot--pull-left"><div class="news-details__header"><span class="news-details__meta text">februrary 9, 2017</span><h1 class="header-large"><strong>Knud Holscher<br> Exhibition opening on January 29!</strong></h1></div><div class="news-details__row"><div class="news-details__author-col"><span class="text author">by Knud Holscher</span></div><div class="news-details__article-col article"><div class="article__rich-text text"><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor,sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p></div></div><div class="news-details__img-col gl-left-lg"><div class="news-details__img lazy-image lazy-image--loaded"><img data-src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg" class="lazy-image__image" src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg"><div class="cell-load__overlay" style=""></div></div></div></div></div>',
      '<div class="news-details gl-bot gl-bot--pull-left"><div class="news-details__header"><span class="news-details__meta text">februrary 9, 2017</span><h1 class="header-large"><strong>100 ton of Danish<br>Design will be installed in Oslo!</strong></h1></div><div class="news-details__row"><div class="news-details__author-col"><span class="text author">by Knud Holscher</span></div><div class="news-details__article-col article"><div class="article__rich-text text"><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor,sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p></div></div><div class="news-details__img-col gl-left-lg"><div class="news-details__img lazy-image lazy-image--loaded"><img data-src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg" class="lazy-image__image" src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg"><div class="cell-load__overlay" style=""></div></div></div></div></div>',
      '<div class="news-details gl-bot gl-bot--pull-left"><div class="news-details__header"><span class="news-details__meta text">februrary 9, 2017</span><h1 class="header-large"><strong>Knud Holscher<br> Exhibition opening on January 29!</strong></h1></div><div class="news-details__row"><div class="news-details__author-col"><span class="text author">by Knud Holscher</span></div><div class="news-details__article-col article"><div class="article__rich-text text"><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor,sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p><p>Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non. Phasellus fringilla lacinia tortor ut auctor. Praesent vl faucibus quam, at convallis odio. Mauris arcu tortor, sagittis vel nisi condimentum, dapibus lacinia lacus. Suspendisse sed sapien ut est sollicitudin feugiat non.</p></div></div><div class="news-details__img-col gl-left-lg"><div class="news-details__img lazy-image lazy-image--loaded"><img data-src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg" class="lazy-image__image" src="images/testmedia/cases/SAS-Hotel-Copenhagen-Denmark-color.jpg"><div class="cell-load__overlay" style=""></div></div></div></div></div>',
    ];

    /*
      Passes back a list of HTML elements to inject into the pagination list.
      The HTML elements returned in the list here will each be wrappen in a
      li by the pagination component.
    */
    this.load = function(index, range, onLoad) {
      var dataSource = mockOverviewData;
      var data = dataSource.slice(index, index + range);

      setTimeout(function () {
        if (onLoad) {
          // If a filter has been set, use the filtered mock data. Else the full mock data.
          onLoad(data);
        }
      }, 200);
    };


    /*
      Loads a single article element to be displayed in the news details page
    */
    this.loadArticle = function (index, onLoad) {
      var data = mockDetailsData[index];

      setTimeout(function () {
        if (onLoad) {
          // If a filter has been set, use the filtered mock data. Else the full mock data.
          onLoad(data);
        }
      }, 200);
    };

    /*
      Gets the total amount of items in the pagination list.
    */
    this.getTotalCount = function (onLoad) {
      if (onLoad) {

        // If a filter has been set, use the filtered mock data. Else the full mock data.
        var length = mockOverviewData.length;
        onLoad(length);
      }
    };
  };

  return NewsService;
});
